# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'land_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QBrush, QPixmap
from PyQt5.QtWidgets import QMainWindow


class Ui_MainWindow(QMainWindow):
    def __init__(self, MainWindow,client_bw=None,id_num=0,parent=None):
        super(Ui_MainWindow, self).__init__(parent)
        self.MainWindow = MainWindow
        self.client=client_bw
        self.id_num=id_num
        self.setupUi()

    def setupUi(self):
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.resize(800, 1000)

        icon = QtGui.QIcon()
        icon_pic = QPixmap("./window resources/机器人.png")
        icon.addPixmap(icon_pic, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        palette = QtGui.QPalette()
        bk = QPixmap("./window resources/background.jpg")
        bk = bk.scaled(self.MainWindow.width(), self.MainWindow.height())
        palette.setBrush(QtGui.QPalette.Background, QBrush(bk))
        # palette.setBrush(MainWindow.backgroundRole(), QBrush(QPixmap("./window resources/background.png").scaled(MainWindow.size(),QtCore.Qt.IgnoreAspectRatio,QtCore.Qt.SmoothTransformation)))
        self.MainWindow.setPalette(palette)

        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(160, 320, 280, 36))
        self.sendButton.clicked.connect(self.callback_of_sendButton)

        self.sendButton.setStyleSheet(
            "QPushButton{background:rgb(50,170,220);border-radius:15px;}QPushButton:hover{background:rgb(0,220,255);}")

        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.sendButton.setFont(font)

        self.sendButton.setObjectName("sendButton")
        self.MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)



    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "聊聊--软件界面"))
        self.sendButton.setText(_translate("MainWindow", "发 送"))



    def callback_of_sendButton(self):
        print("发送了信息！")



    def show(self):
        self.MainWindow.setWindowFlags(QtCore.Qt.MSWindowsFixedSizeDialogHint)
        self.MainWindow.show()


    def closeEvent(self, event):
        if self.client:
            mes = "OFFLINE"
            mes_to_server = mes.encode('utf-8')
            self.client.sendall(mes_to_server)  # 发送数据到客户端
            time.sleep(0.01)
        print("关闭")
        # friend_state = "OFFLINE"



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    chat_window = Ui_MainWindow(QtWidgets.QMainWindow())
    chat_window.setupUi()
    chat_window.show()
    sys.exit(app.exec_())