# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'land_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QBrush, QPixmap
from PyQt5.QtWidgets import QMainWindow
import time, threading
import multiprocessing
import friend_viewer_2


class Ui_MainWindow(QMainWindow):
    def __init__(self, MainWindow, parent=None):
        super(Ui_MainWindow, self).__init__(parent)
        self.MainWindow = MainWindow


    def setupUi(self):
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.resize(600, 400)

        icon = QtGui.QIcon()
        icon_pic = QPixmap("./window resources/present10.png")
        icon.addPixmap(icon_pic, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        palette = QtGui.QPalette()
        bk = QPixmap("./window resources/background2.png")
        bk = bk.scaled(self.MainWindow.width(), self.MainWindow.height())
        palette.setBrush(QtGui.QPalette.Background, QBrush(bk))
        # palette.setBrush(MainWindow.backgroundRole(), QBrush(QPixmap("./window resources/background.png").scaled(MainWindow.size(),QtCore.Qt.IgnoreAspectRatio,QtCore.Qt.SmoothTransformation)))
        self.MainWindow.setPalette(palette)

        self.landButton = QtWidgets.QPushButton(self.centralwidget)
        self.landButton.setGeometry(QtCore.QRect(160, 320, 280, 36))
        self.landButton.clicked.connect(self.callback_of_landbutton)

        self.landButton.setStyleSheet("QPushButton{background:rgb(50,170,220);border-radius:15px;}QPushButton:hover{background:rgb(0,220,255);}")

        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.landButton.setFont(font)

        self.landButton.setObjectName("Button_land")
        self.MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)



    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "聊聊--登陆界面"))
        self.landButton.setText(_translate("MainWindow", "登 陆"))



    def callback_of_landbutton(self):
        print("点击了登陆按钮！")
        self.friend_window = friend_viewer_2.Ui_MainWindow(QtWidgets.QMainWindow(), self)
        self.friend_window.setupUi()
        self.friend_window.show()

        # chat_window = chat_viewer_2.Ui_MainWindow(QtWidgets.QMainWindow())
        # app_chat_window = QtWidgets.QApplication(sys.argv)
        # t_new = threading.Thread(target=chat_window.run)
        # t_new.start()
        # sys.exit(app_chat_window.exec_())


        # p_new = multiprocessing.Process(target=self.AI_talk)
        # p_new.start()

        # self.chat_window = QtWidgets.QMainWindow()
        # chat_ui=chat_viewer.Ui_MainWindow()
        # chat_ui.setupUi(self.chat_window)
        # self.chat_window.show()


    def AI_talk(self):

        for i in range(50):
            time.sleep(1)
            print(i)


    def show(self):
        self.MainWindow.setWindowFlags(QtCore.Qt.MSWindowsFixedSizeDialogHint)
        self.MainWindow.show()





if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow(QtWidgets.QMainWindow())
    ui.setupUi()
    ui.show()
    sys.exit(app.exec_())






